### ISSUE TITLE
Jog L & R switches appear to stop working after touchscreen menu use

### ISSUE THREAD

**Issue by nlroth** [hugen79/NanoVNA-H#13]
I have found a problem with your Oct 9 4-trace release, where I use only the touchscreen and I select CONFIG and then the VERSION menu items and go back up the menu tree to select something else, then back to the version menu and then clear the menu from the screen.
Now, if I try to use the jog switch, I get the menu appear with ENTER but I can no longer get any menu items to highlight. 
It appears the switches are being sensed because if I press Enter to bring up the root menu and then press the Right key 7 times, the menu disappears - but nothing was highlighted.
I tried the same menu sequence on QRP's 0.4.3 release and it is OK.
Thanks.
Larry

**Comment by hugen79** [comment]
Let me test it first and it will be improved later.

**Comment by nlroth** [comment]
The jog switches appear to have no issue with your latest release. The problem may have been due to an overflow somewhere. You can close

**Comment by hugen79** [comment]
> The jog switches appear to have no issue with your latest release. The problem may have been due to an overflow somewhere. You can close

Trying to replace r5 with a 1k ohm resistor should improve.
hugen
