### ISSUE TITLE
Just FYI C11 "problem" add -std=gnu11 to "makeflie" compiler options 

### ISSUE THREAD

**Issue by JulyJim** [hugen79/NanoVNA-H#17]
Current release, as of 11/18/2019,  has a same issue with C11 complier as NanoVNA did.  
Instead of patching all problem occurrences - about 10 or so, I choose to follow "make" suggestion and added , cheap hack,  

# Compiler options here.
# added -std=gnu11
ifeq ($(USE_OPT),)
  USE_OPT = -std=gnu11 -O2  -ggdb -fomit-frame-pointer -falign-functions=16 --specs=nano.specs -fstack-usage
endif

**Comment by hugen79** [comment]
Thanks, I will modify it.
