### ISSUE TITLE
Pressing right side of H4 causes random menu responses

### ISSUE THREAD

**Issue by hwalker6742** [hugen79/NanoVNA-H#28]
I'm getting feedback from members at groups.io, and verified by myself, about the following issue:

   - If a menu is brought up and pressure is applied to the right side of the case, random menu choices occur.

A working solution has been proposed by one of the groups.io members at: https://groups.io/g/nanovna-users/message/10369 .

- Herb

**Comment by hugen79** [comment]
I'm very sorry for this problem, and I will fix the plastic case as soon as the Chinese factory resumes normal work.
