### ISSUE TITLE
NanoVNA-H4:  "scan" console cmd causes display to dim

### ISSUE THREAD

**Issue by hwalker6742** [hugen79/NanoVNA-H#34]
Sending a scan console command (i.e. "scan 50000 30000000) to the NanoVNA-H4 causes the display to dim.  The display stays dim until a "resume" console command sent.  I'm pretty sure this interaction between the display and the scan command is unintentional.

This issue has been verified by other NanoVNA-H4 users at nanovna-users@groups.io.

- Herb

**Comment by hugen79** [comment]
Yes, the display will be paused when using the scan command. At this time, it does not make sense to check the screen display trace. So I hope to reduce the screen brightness and save current consumption.

hugen
