### ISSUE TITLE
Device is not recognized by host with Type-C to Type-C  cable.

### ISSUE THREAD

**Issue by cho45** [hugen79/NanoVNA-H#4]
https://github.com/hugen79/NanoVNA-H/blob/master/doc/Schematic_nanovna_Sheet-1_20190711140429.jpg

Type-C CC1 seems unconnected to any pin. Does CC1 need to be connected to GND through a 5.1kΩ resistor?

**Comment by hugen79** [comment]
Thank you for your feedback, I am aware of this error, the new version of the Schematic has fixed this issue.
https://github.com/hugen79/NanoVNA-H/blob/master/doc/Schematic_nanovna-H_Sheet-1_2019092.png

**Comment by cho45** [comment]
Thank you fo repliyng! Great!
