### ISSUE TITLE
Make error F303_ChibiOS_18

### ISSUE THREAD

**Issue by x893** [hugen79/NanoVNA-H#44]
Hello,
i clone
https://github.com/hugen79/NanoVNA-H/tree/F303_ChibiOS_18

and make return next error

Makefile:122: ChibiOS/test/oslib/oslib_test.mk: No such file or directory
make: *** No rule to make target 'ChibiOS/test/oslib/oslib_test.mk'.  Stop.

Can you give a little instruction to compile ?

Thanks in advance

**Comment by hugen79** [comment]
Hello x893, I am sorry to reply to you late, you need to synchronize the ChibiOS subroutine.

`$ git submodule update --init --recursive`

If there are still problems with compilation, I can send you the source code containing ChibiOS via email.

hugen
