### ISSUE TITLE
Is it normal for the readouts to be this low when uncalibrated?

### ISSUE THREAD

**Issue by goscickiw** [hugen79/NanoVNA-H#47]
I have been using the NanoVNA-H for some time now, and I've been wondering this for a while, but never cared about it too much as it worked fine when calibrated. However, recently I bought a S-A-A-2 and it doesn't seem to have this problem when uncalibrated, so I finally decided to ask.

The uncalibrated magnitude measurements for CH0 are about -20 dB when nothing is connected, and for CH1 they're -10 dB when CH0 and CH1 are connected together with coax. This seems oddly low, as in both cases they should be close to 0 dB. I remember that it didn't have this issue out of the box, but it might have been pre-calibrated by the seller, and I did a firmware upgrade shortly after receiving it which most likely removed the original calibration.

This is how it looks like when not calibrated:
![IMG_1715](https://user-images.githubusercontent.com/39399945/92302403-313fe980-ef6c-11ea-9fd4-9f22c5a816e5.JPG)

With calibration for comparison:
![IMG_1714](https://user-images.githubusercontent.com/39399945/92302415-49b00400-ef6c-11ea-8650-b051cf2b9808.JPG)

Is it normal, or does it mean that it's defective, or a crappy clone? (I didn't buy it from the official alibaba link, but from a local seller [here](https://www.konektor5000.pl/index.php?p4509,nanovna-h-najmniejszy-analizator-antenowy-50khz-1500mhz-dotykowy-wyswietlacz-2-8-najnowsza-wersja-h))

**Comment by hugen79** [comment]
Yes, the original NanoVNA design has this problem. The reference signal is too high, resulting in low uncalibrated data. This problem can be solved by calibration. SAA2 uses a different design.

**Comment by goscickiw** [comment]
Thanks, looks like my NanoVNA is fine then.
