### ISSUE TITLE
Cannot connect via USB immediately after plugging in

### ISSUE THREAD

**Issue by Ho-Ro** [hugen79/NanoVNA-H#58]
I reported it already at [DiSlord](https://github.com/DiSlord/NanoVNA-D/issues/11), but it seems to be an upstream issue.

**Comment by hugen79** [comment]
It may be that your windows 7 is missing system files, we recommend using windows 10.

**Comment by Ho-Ro** [comment]
Closed with [this commit](https://github.com/hugen79/NanoVNA-H/blame/fe095116f369054c0d8bb49ff84ef44b24ffc693/usbcfg.c#L73).
