### ISSUE TITLE
tlv320aic3204 driver

### ISSUE THREAD

**Issue by qrp73** [hugen79/NanoVNA-H#6]
Hi, I found there is a difference in the tlv320aic3204 driver in comparison with edy555 version:

Here is original edy555 code:
```
    I2CWrite(AIC3204_ADDR, 0x3b, 0); /* Unmute Left MICPGA, Gain selection of 32dB to make channel gain 0dB */
    I2CWrite(AIC3204_ADDR, 0x3c, 0); /* Unmute Right MICPGA, Gain selection of 32dB to make channel gain 0dB */
```

Here is your code:
```
    I2CWrite(AIC3204_ADDR, 0x3b, 5); /* Unmute Left MICPGA, Gain selection of 32dB to make channel gain 2.5dB */
    I2CWrite(AIC3204_ADDR, 0x3c, 5); /* Unmute Right MICPGA, Gain selection of 32dB to make channel gain 2.5dB */
```

Could you please explain what is the reason for this? 
Thanks

**Comment by hugen79** [comment]
This reduces some of the measurement range of positive gain, but results in better loss measurement dynamics.This is not necessarily suitable for all measurements, but it can be a little helpful for loss measurements.

**Comment by hugen79** [comment]
This reduces some of the measurement range of positive gain, but results in better loss measurement dynamics.This is not necessarily suitable for all measurements, but it can be a little helpful for loss measurements.
