### ISSUE TITLE
could not open the screenshot bmp file.

### ISSUE THREAD

**Issue by tumuyan** [hugen79/NanoVNA-H#63]
[28210047.zip](https://github.com/hugen79/NanoVNA-H/files/7512850/28210047.zip)
I use a nanovna-h4 whih hw4.2 & fw NanoVNA-H4_20211009, 
when I insect a TF card, click menu sd card - screenshot, bmp file could be saved in the card, but it could not  open it in my pc

**Comment by hugen79** [comment]
Please test if the new version has worked properly.

**Comment by tumuyan** [comment]
> Please test if the new version has worked properly.

Now it works
