### ISSUE TITLE
Bootup hangs after touchscreen calibration

### ISSUE THREAD

**Issue by nlroth** [hugen79/NanoVNA-H#7]
After flashing ALL_FF to clear memory and then flashing NanoVNA-H__900_aa_20191003.dfu the device will boot every time with no issue. 

I then calibrate touchscreen - not issues while device stays on.
If device is turned-off, device hangs at bootup every time only showing version screen.

Re-flashed hugen_900_(1500)_ch_sept-24-19.dfu - no issues with lockup.
Re-flashed NanoVNA-H__900_ch_20191003.dfu version - no problem.

Both 800 & 900 AA versions have same issue **BUT** 800 version boots up showing TDR time at bottom of display and produces unrecognized USB error on PC - DFU mode works though.

**Comment by hugen79** [comment]
Thanks for the feedback, the bug has been corrected, please try the new version.
