### ISSUE TITLE
NanoVNA H4 does not starts

### ISSUE THREAD

**Issue by DimSUN19** [hugen79/NanoVNA-H#78]
When it switch on there are no any changes on display and no response to toush the display or press the button. Howerware you can put it into programming mode by POWER+BUTTON. Also you can update the firmware. I already did clearconfig 1234 and update the firmware. No result
![IMG20230517155948](https://github.com/hugen79/NanoVNA-H/assets/133879191/56364923-805f-4fbc-9658-978949453e2c)

**Comment by hugen79** [comment]
Please remove the protective film.
