### ISSUE TITLE
Display update leaves larger font artifact in 'AA' version

### ISSUE THREAD

**Issue by nlroth** [hugen79/NanoVNA-H#8]
(**Not a big issue**)
The CAL font (C0) at left side of display is not completely erased - old smaller font routine doesn't remove larger font completely.
Also, larger font extends beyond button slightly at right side for **Correction** and **Touch_test** menu buttons.
![larger font issues ](https://user-images.githubusercontent.com/48253208/66135441-f9942900-e5c7-11e9-8e2a-ffdf5371f77e.jpg)

**Comment by hugen79** [comment]
Thanks for the feedback, the bug has been corrected, please try the new version.
