### ISSUE TITLE
New version no longer has AA like in 2020

### ISSUE THREAD

**Issue by tuvok81** [hugen79/NanoVNA-H#80]
Hello,
I have a question and I currently have the 1.0.45 from 2020 or so on my NanoVNA 
At that time, version AA was installed for a better view with only 2 measuring points.
but with the new versions I don't understand which one is similar to the AA version from back then.
It would be nice if someone could help me.

![20231211_182153](https://github.com/hugen79/NanoVNA-H/assets/30367063/4adddd10-9568-491f-8cba-d6f4fa6747ca)

**Comment by hugen79** [comment]
The latest version already uses larger fonts and is no longer available in AA.
