### ISSUE TITLE
Why so many different names for the firmware .DFU files?

### ISSUE THREAD

**Issue by Basilisvirus** [hugen79/NanoVNA-H#89]
Why are there multiple options to download for NanoVNA-H?  
What is the difference between:  
NanoVNA-H-MS_20240220.dfu  
NanoVNA-H-SI_20240220.dfu  
 NanoVNA-H-SM_ST_20240220.dfu  ?
![image](https://github.com/user-attachments/assets/65f039ad-eab9-4bec-8646-365435c18ca7)

**Comment by ChrisHVL** [comment]
I cant give the anwswer, but for the newest firmware you may look at @Dislord rep...

**Comment by Basilisvirus** [comment]
Figured it out, at the back of my nanoVNA it says "HW version: 3.6_MS" so this is the clock generation source, the MS part!
